ifdef::env-github[]
:note-caption: :pencil2:
endif::[]

= Microsoft Authentication Package v1.0
:toc: macro

The msv1_0 authentication package (AP) supports local machine logons.
It is also the security package (SP) for NTLM challenge-response authentication on a network.

toc::[]

== Functions

The protocol messages that msv1_0 supports is documented on MSDN and included here for conveniencefootnote:[https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/ne-ntsecapi-msv1_0_protocol_message_type[MSV1_0_PROTOCOL_MESSAGE_TYPE enumeration (ntsecapi.h)]]:

[%header]
|===
| Id     | Message Type               | CLI Support        | NT Version | Internal Function
| `0x00` | `Lm20ChallengeRequest`     | :heavy_check_mark: | _All_      | `MspLm20Challenge`
| `0x01` | `Lm20GetChallengeResponse` | :x:                |            | `MspLm20GetChallengeResponse`
| `0x02` | `EnumerateUsers`           | :heavy_check_mark: | _All_      | `MspLm20EnumUsers`
| `0x03` | `GetUserInfo`              | :heavy_check_mark: | _All_      | `MspLm20GetUserInfo`
| `0x04` | `ReLogonUsers`             | :heavy_minus_sign: | _None_     | `MspLm20ReLogonUsers`
| `0x05` | `ChangePassword`           | :x:                |            | `MspLm20ChangePassword`
| `0x06` | `ChangeCachedPassword`     | _Planned_          | _All_      | `MspLm20ChangePassword`
| `0x07` | `GenericPassthrough`       | _Planned_          | _All_      | `MspLm20GenericPassthrough`
| `0x08` | `CacheLogon`               | :heavy_check_mark: | _All_      | `MspLm20CacheLogon`
| `0x09` | `SubAuth`                  | :x:                |            | `MspNtSubAuth`
| `0x0A` | `DeriveCredential`         | :heavy_check_mark: | _All_      | `MspNtDeriveCredential`
| `0x0B` | `CacheLookup`              | _Planned_          | _All_      | `MspLm20CacheLookup`
| `0x0C` | `SetProcessOption`         | :heavy_check_mark: | _All_      | `MspSetProcessOption`
| `0x0D` | `ConfigLocalAliases`       | :x:                |            | `MspConfigLocalAliases`
| `0x0E` | `ClearCachedCredentials`   | :heavy_check_mark: | `>=6.0`    | `MspLm20ClearCachedCredentials`
| `0x0F` | `LookupToken`              | :x:                |            | `MspLookupToken`
| `0x10` | `ValidateAuth`             | :x:                |            | `MspValidateAuth`
| `0x11` | `CacheLookupEx`            | _Planned_          | `>=6.2`    | `MspLm20CacheLookup`
| `0x12` | `GetCredentialKey`         | :heavy_check_mark: | `>=6.2`    | `MspGetCredentialKey`
| `0x13` | `SetThreadOption`          | :x:                |            | `MspSetThreadOption`
| `0x14` | `DecryptDpapiMasterKey`    | _Planned_          | `>=6.4`    | `MspDecryptDpapiMasterKey`
| `0x15` | `GetStrongCredentialKey`   | _Planned_          | `>=6.4`    | `MspGetStrongCredentialKey`
| `0x16` | `TransferCred`             | :heavy_check_mark: | `>=10.0`   | `MspTransferCreds`
| `0x17` | `ProvisionTbal`            | :heavy_check_mark: | `>=10.0`   | `MspProvisionTbal`
| `0x18` | `DeleteTbalSecrets`        | :heavy_check_mark: | `>=10.0`   | `MspDeleteTbalSecrets`
|===

NOTE: The internal function for each message type will be located in `msv1_0.dll`.

Each function may be called in Lsa Whisperer using `sspi msv1_0 --function <name>`.

=== CacheLogon

This dispatch routine caches logon information in the logon cache.
MSV1_0 will check to make sure the client request came from the same process.

```
msv1_0 -f CacheLogon --domain {name} --account {name} [--computer name] {--hash {value} | --pass {value}} [--mitlogon {upn}] [--suppcreds {data}] [--delete] [--smartcard]
```

=== CacheLookup

...
For a cached smart card logon the issuer and subject name will be used as the user name and domain name, the credential type will be raw, and the credential data will be the SHA1 hash of the certificate.

```
msv1_0 -f CacheLookup --account {name} [--domain name] --credtype {name} --cred {ascii hex}
```

=== CacheLookupEx

This dispatch routine looks up the local logon in the cache.
The `SeTcbPrivilege` is required.

```
msv1_0 -f CacheLookupEx ...
```

=== ChangeCachedPassword

This dispatch routine changes a password in the logon cache.
This is used when the password is changed on the domain controller using some other mechanism and the locally cached version needs to be updated to match the new value.
For example, RAS handles changing the passwords on the domain but then needs to update the cached copy so the user can still access servers.
The `SeTcbPrivilege` is required if you are changing the cached entry for someone else.

```
msv1_0 -f ChangeCachedPassword --domain {name} --account {name} --oldpass {password} --newpass {password}
```

=== ChangePassword

Not implemented.
Appears at first to be coercible, but LSASS will impersonate itself and remove the admin (`S-1-5-32-544`) sid before making a connection to another computer.

=== ClearCachedCredentials

Clear the credentials in the local NTLM logon cache.
The `SeTcbPrivilege` is required.

```
msv1_0 -f ClearCachedCredentials
```

=== DecryptDpapiMasterKey

...

```
msv1_0 -f DecryptDpapiMasterKey ...
```

=== DeleteTbalSecrets

Clear the Trusted Boot Auto-Logon (TBAL) secrets in the System vault.<sup>2</sup>

```
msv1_0 -f DeleteTbalSecrets
```

=== DeriveCredential

Get the [SHA1 HMAC](https://en.wikipedia.org/wiki/HMAC) for a provided message using an NT OWF or SHA1 OWF password as the key, specified by the logon session id.
The `--sha1v2` argument specifies to use the SHA1 OWF password instead of the NT OWF password.
The `SeTcbPrivilege` may be required when specifying an id for another logon session but still need to verify that.

```
msv1_0 -f DeriveCredential --luid {session id} [--sha1v2] --message {ascii hex}
```

=== EnumerateUsers

Enumerates all interactive, service, and batch logons managed by MSV1_0.
The machine account logon will not be included in the list.

```
msv1_0 -f EnumerateUsers
```

=== GenericPassthrough

This dispatch routine passes any of the other dispatch routines to the domain controller.
The authentication package on the domain controller may choose to reject certain dispatch requests.

```
msv1_0 -d -f {function name} [function arguments]...
```

=== GetCredentialKey

Get the primary credential keys for a logon session.
The keys will either be the NT and SHA OWF hashes or the SHA hash and the DPAPI key.
The `SeTcbPrivilege` is required and credential isolation must also not be enabled.

```
msv1_0 -f GetCredentialKey --luid {session id}
```

=== GetStrongCredentialKey

...

```
msv1_0 -f GetStrongCredentialKey ...
```

=== GetUserInfo

Get information about a session id.

```
msv1_0 -f GetUserInfo --luid {session id}
```

=== Lm20ChallengeRequest

Get a challenge that may be delivered to a host that initiated an NTLMv2 logon.
Once a challenge response is received, it may be passed to `LsaLogonUser` with a `LogonType` of `MsV1_0Lm20Logon` to complete the logon.

```
msv1_0 -f Lm20ChallengeRequest
```

=== ProvisionTbal

Provision the Trusted Boot Auto-Logon (TBAL) LSA secrets for a logon session.footnote:[https://www.passcape.com/index.php?section=blog&cmd=details&id=38#a6[What is Trusted Boot Auto-Logon (TBAL)?]]
The host is required to be actively kernel debugged for the function to succeed.

```
msv1_0 -f ProvisionTbal --luid {session id}
```

=== SetProcessOption

Enable or disable an option for the calling process.
The `SeTcbPrivilege` is required.
The currently known set of process options include:

- `AllowBlankPassword`
- `AllowOldPassword`
- `DisableAdminLockout`
- `DisableForceGuest`
- `TryCacheFirst`

MSV1_0 may internally check for one these options using `NtLmCheckProcessOption`.

```
msv1_0 -f SetProcessOption --option {process option} [--disable]
```

=== SetThreadOption

Enable or disable an option for the calling thread.
The set of options are the same as with the `SetProcessOption` command but they will take precedence over process options.
The `SeTcbPrivilege` is required.

```
msv1_0 -f SetThreadOption --option {thread option} [--disable]
```

=== TransferCred

Transfer data from one logon session to another logon session.
The specific data that is transferred and privileges that may be required are still being determined.

```
msv1_0 -f TransferCred --sluid {session id} --dluid {session id}
```

== Sub-authentication Packages

Msv1_0 supports registering custom sub-authentication packages for extra user validation for local logons.
The only Micosoft developed sub-authentication package that could be identified was the "Microsoft IIS sub-authenticiation handler" implemented in the file `iissuba.dll`.
The `iissuba.dll` package has not shipped with Windows for a long time - hence it has not been included in the LSA Whisperer project.