ifdef::env-github[]
:note-caption: :pencil2:
endif::[]

= Negotiate Extender (NegoExtender)
:toc: macro

Negoexts is the security package (SP) for the SPNEGO Extended Negotiation (NEGOEX) protocol.
Negoexts https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd560645(v=ws.10)[was added in NT 6.1] to allow https://learn.microsoft.com/en-us/previous-versions/ff468736(v=msdn.10)[the Negotiate SSP to support more than NTLM and Keberos and to extend the GSS-API with additional features].

Microsoft waited until 2020 to publish a technical document on https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-negoex/0ad7a003-ab56-4839-a204-b555ca6759a2[NEGOEX], which was 11 years after the release of NT 6.1.
They did however apply for a US patent in 2008 on the https://patents.google.com/patent/US20090328140["Advanced Security Negotiation Protocol"] which was the original name for NEGOEX and an https://datatracker.ietf.org/doc/draft-zhu-negoex/[RFC draft] for NEGOEX in 2011.
The patent defined the Windows Security Type (WST) Library message which is not documented on MSDN but is the basis of the NEGOEX message and is referenced in all versions of the NegoExtender SSP.

Due to its design, negoexts also supports authentication package (AP) functions for user logons and package calls (e.g., `LsaApCallPackage`).
The NegoExtender compatable SSPs include CloudAP, LiveSSP, and PKU2U.

toc::[]

== Functions

The protocol messages that negoexts supports is not documented by Microsoft but is provided here.
Supporting negoexts commands is currently not a priority for Lsa Whisperer.

[%header]
|===
| Id    | Message Type        | CLI Support | NT Version | Internal Function
| `0x1` | `GetCredUIContext`  |             | `>=6.1`    | `WSTGetCredUIContext`
| `0x2` | `UpdateCredentials` |             | `>=6.1`    | `WSTUpdateCredentials`
| `0x3` | `LookupContext`     |             | `>=6.1`    | `WSTLookupContext`
| `0x4` | `FlushContext`      |             | `>=6.1`    | `WSTFlushContext`
|===