ifdef::env-github[]
:note-caption: :pencil2:
endif::[]

= NegoExtender Security Package
:toc: macro

NegoExtender is the security package (SP) for SPNEGO Extended Negotiation (NEGOEX).
NEGOEX was added in NT 6.1 to allow the Negotiate SSP to support more than just NTLM and Keberos (e.g., PKU2U) and to extend the GSS-API with additional features.
Microsoft provides documentation for NegoExtender's https://learn.microsoft.com/en-us/previous-versions/ff468736(v=msdn.10)[backgound and design] as well as a technical document for https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-negoex/0ad7a003-ab56-4839-a204-b555ca6759a2[NEGOEX].
Due to its design, NegoExtender also supports authentication package (AP) functions for user logons and package calls (e.g., `LsaApCallPackage`).
The NegoExtender compatable SSPs include CloudAP, LiveSSP, and PKU2U.

toc::[]

== Functions

The protocol messages that negoexts supports is not documented by Microsoft but is provided here.
Supporting negoexts commands is currently not a priority for Lsa Whisperer.

[%header]
|===
| Id    | Message Type           | NT Version
| `0x1` | `WSTGetCredUIContext`  | `>=6.1`
| `0x2` | `WSTUpdateCredentials` | `>=6.1`
| `0x3` | `WSTLookupContext`     | `>=6.1`
| `0x4` | `WSTFlushContext`      | `>=6.1`
|===

NOTE: The significance of the acronym WST could not be identified.
