ifdef::env-github[]
:note-caption: :pencil2:
endif::[]

= Public Key User 2 User (PKU2U)
:toc: macro

The pku2u authentication package (AP) supports peer-to-peer logons.
It is also the security package (SP) for the https://datatracker.ietf.org/doc/id/draft-zhu-pku2u-09.txt[Public Key Cryptography Based User-to-User] protocol, a GSS-API compliant alternative to Kerberos V which does not require a Key Distribution Center (KDC).
Pku2u https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd560634(v=ws.10)[was added in NT 6.1] to allow https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd560662(v=ws.10)[users with linked online IDs] to share files via https://en.wikipedia.org/wiki/Features_new_to_Windows_7#HomeGroup[HomeGroup], a Windows feature that was removed in https://support.microsoft.com/en-us/windows/homegroup-removed-from-windows-10-version-1803-07ca5db1-7bca-4d11-68a3-a31ff4a09979[NT 10 1803].
Pku2u is now used to allow https://syfuhs.net/how-authentication-works-when-you-use-remote-desktop[Azure AD (AAD) joined hosts to authenticate with other AAD joined hosts for RDP, SMB, and another network protocol].

toc::[]

== Functions

The protocol messages that pku2u supports is not documented by Microsoft but is provided here.
The message IDs, request buffers, and response buffers for each function align with their equivalent function in the kerberos package.
As such, the message type names were choosen to align with how Microsoft named them for kerberos.

[%header]
|===
| Id     | Message Type        | CLI Support        | NT Version | Internal Function
| `0x0f` | PurgeTicketCacheEx  | _Planned_          | `>=6.1`    | Pku2uPurgeTicketEx
| `0x14` | QueryTicketCacheEx2 | _Planned_          | `>=6.1`    | Pku2uQueryTicketCacheEx2
|===

NOTE: The internal function will be located in `pku2u.dll`.

=== PurgeTicketCacheEx

Remove an individuel ticket or all tickets from the ticket cache for a logon session.

```
pku2u PurgeTicketCacheEx [--all] ...
```

=== QueryTicketCacheEx2

Get the tickets for a logon session.
`SeTcbPrivilege` is not required to make the call, but is required for the call to return data.

```
pku2u QueryTicketCacheEx2 --luid {session id}
```