ifdef::env-github[]
:note-caption: :pencil2:
endif::[]

= Windows Digest

Wdigest is an authentication package (AP) that was introduced in NT 5.1 to support digest authentication.
It is also the security package (SP) for the https://en.wikipedia.org/wiki/Digest_access_authentication[Digest Access protocol].
The package only supports a single protocol message which is only reachable using the `CallPackagePassthrough` function.
Its `CallPackage` and `CallPackageUntrusted` functions are available but return `SEC_E_UNSUPPORTED_FUNCTION`.

== Functions

The protocol messages that wdigest supports is not documented by Microsoft but is provided here.

[%header]
|===
| Id     | Message Type   | CLI Support | NT Version | Internal Function
| `0x1a` | `VerifyDigest` | _Planned_   | _All_      | `DigestPackagePassthrough`
|===

NOTE: The internal function will be located in `wdigest.dll`.

=== VerifyDigest

The request may be used to verify a plaintext password or OWF hash for a user.
If the provided data is valid the response will contain a session key and PAC for the user.
Request data is marshalled as a `DIGEST_BLOB_REQUEST` with responses sent as `DIGEST_BLOB_RESPONSE`.

```
wdigest VerifyDigest ...
```
