// Only the data for the wlidsvc serialization service
// Does not include the data for the RPC interface
//
// The structures were auto generated using NtObjectManager, livessp, and the MSA plugin for cloudap.
// https://www.tiraniddo.dev/2020/07/generating-ndr-type-serializers-for-c.html
//
// The structure names were applied using named identified through manual analysis.
// The names may be slightly off from Microsoft's internal IDL due to that, but the formatting should be correct. 

// Guessed name
struct _WLIDIdentityProperty {
    int type;
    char[] Value; // byte[]
};

// Client serialized data
struct _WlidPropertyBag {
    int Count;
    struct _WLIDIdentityProperty[] Properties;
};

// Guessed name
struct _WLIDCredentialAttribute {
    int Type;
    wchar_t[] Value;
};

// Guessed name
struct _WLIDCredentialsType {
    int Member0; // ENUM16
    struct _WLIDCredentialAttribute Member8;
};

// Client serialized data
struct _WLIDCredentialBag {
    int Member0; // ENUM16
    int Count;
    struct _WLIDCredentialsType[] Credentials;
};

// Guessed name
struct _WLIDTokenParams {
    char* Member0;
    char* Member8;
    char* Member10;
    char* Member18;
    int Member20;
    int Member24; // ENUM16
};

// Client serialized data
struct _UnsignedProofOfPossessionTokenParameter {
    struct _WLIDTokenParams TokenParams;
    int Member28;
    int Member2C;
    int Member30;
    char[] Member38; // byte[]
};

// Guessed name
struct _WLIDSignedTokens {
    char* Member0;
    char* Member8;
    char* Member10;
    char* Member18;
    int Member20;
    int Member24; // ENUM16
};

// Client serialized data
struct _ProofOfPossessionTokenBag {
    int Count;
    struct _WLIDSignedTokens[] Tokens;
};